--TABLE DE APPLICATIONS
CREATE TABLE JSEC2_APPLICATION(
	ID NUMBER(19,0) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	SID VARCHAR2(32) NOT NULL,
	SECRET VARCHAR(32) NOT NULL,
	CONSTRAINT J2_APP_ID PRIMARY KEY ("ID"),
	CONSTRAINT UQ_J2_APP_NAME UNIQUE ("NAME"),
	CONSTRAINT UQ_J2_APP_SID UNIQUE ("SID")
);

-- TABLE DE REGRAS
CREATE TABLE JSEC2_RULE(
	ID NUMBER(19,0) NOT NULL,
	RULE_TYPE VARCHAR2(16) NOT NULL,
	OPERATOR_TYPE VARCHAR2(16) NOT NULL,
	RULE_VALUE VARCHAR2(32) NOT NULL,
	DESCRIPTION VARCHAR2(64) NOT NULL,
	CONSTRAINT J2_RUL_ID PRIMARY KEY("ID")
);

-- TABLE DE PAPEIS
CREATE TABLE JSEC2_ROLE(
	ID NUMBER(19,0) NOT NULL,
	NAME VARCHAR2(24) NOT NULL,
	CONSTRAINT J2_ROL_ID PRIMARY KEY("ID"),
	CONSTRAINT UQ_J2_ROL_NAME UNIQUE ("NAME")
);

--TABLE DE LOTACAO
CREATE TABLE JSEC2_LOCATION(
	ID NUMBER(19,0) NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	PROPERTIES XMLTYPE,
	CONSTRAINT J2_LOC_ID PRIMARY KEY("ID"),
	CONSTRAINT UQ_J2_LOC_NAME UNIQUE ("NAME")
);

--TABLE DE USUARIO
CREATE TABLE JSEC2_USER(
	ID NUMBER(19,0) NOT NULL,
	LOGIN VARCHAR2(24) NOT NULL,
	EMAIL VARCHAR2(32) NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	PASSWD VARCHAR2(32),
	ROOT NUMBER(1,0),
	PROPERTIES XMLTYPE,
	CONSTRAINT J2_USR_ID PRIMARY KEY("ID"),
	CONSTRAINT UQ_J2_USR_LOGIN UNIQUE ("LOGIN"),
	CONSTRAINT UQ_J2_USR_NAME UNIQUE ("NAME"),
	CONSTRAINT UQ_J2_USR_EMAIL UNIQUE ("EMAIL")
);

